class ExceedsMemoryError(Exception): ...


class EmptyStreamError(Exception): ...


class InvalidKeyError(Exception): ...


class OversizedBlockError(Exception): ...


class ReverseCallExpected(Exception): ...


class ResetRequiredError(Exception): ...